accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

api/urls.py
from django.urls import path
from .views import favorite_baby_name

urlpatterns = [
    path('favorite/', favorite_baby_name, name='favorite_baby_name'),
]

babynamer/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include(('app.urls', 'app'))),  # using a tuple to define the namespace
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app/baby_name_card.html
<div class="card" style="width: 18rem; height: 10rem">
    <div class="card-body">
        <h5 class="card-title">
            {{name.rank}}:
            <a href="{% url 'app:baby_name_detail' name.name %}">{{ name.name }}</a>
            <span class="heart" id="{{ name.name }}">
                {% if name.name in favorites %}
                    <i class="bi bi-heart-fill"></i>
                {% else %}
                    <i class="bi bi-heart"></i>
                {% endif %}
            </span>
        </h5>
        {% for tag in name.tags %}
        {% if tag.value != 'nan' %}
            <span class="badge badge-pill badge-primary">
                {% if tag.value == True %}
                    {{ tag.key|title }}
                {% else %}
                    {{ tag.value|title }}
                {% endif %}</span>
        {% endif %}
        {% endfor %}
        <p class="card-text">
            {% if name.description|length > 5 %}
                {{ name.description|truncatechars:60 }}
            {% else %}
                Currently processing {{name.name}}, check back later.
            {% endif %}
        </p>
    </div>
  </div>

templates/app/baby_name_details.html
{% extends "app/base.html" %}
{% load static %}
{% load humanize %}
{% block title %}
    <title> {{ name.name }} - BabyNamer.AI</title>
{% endblock %}

{% block header %}
{% endblock %}


{% block content %}
    <h1>{{ name.name }}
        <span class="heart" id="{{ name.name }}">
                    {% if name.name in favorites %}
                        <i class="bi bi-heart-fill"></i>
                    {% else %}
                        <i class="bi bi-heart"></i>
                    {% endif %}
                </span>
    </h1>
        <!-- Check if user is a superuser, and if so, display link to admin page -->
        {% if request.user.is_authenticated and request.user.is_superuser %}
            <small>(ADMIN ONLY<a href="{% url 'admin:app_babyname_change' name.name %}">Edit in Admin</a>)</small>
        {% endif %}

        {% for tag in tags %}
        {% if tag.value != 'nan' %}
            <span class="badge badge-pill badge-primary">
                {% if tag.value == True %}
                    {{ tag.key|title }}
                {% else %}
                    {{ tag.value|title }}
                {% endif %}</span>
        {% endif %}
        {% endfor %}
    <table class="table">
        <tbody>
            <tr>
                <th>Gender</th>
                <td>{{ name.gender }}</td>
            </tr>
            {% if name.boy_rank is None and name.girl_rank is None %}
                <tr>
                    <th>Unique Name</th>
                    <td><h3>Not enough data for us to tell much about this name</h3></td>
            </tr>
            {% else %}
                {% if name.gender in 'Male,Unisex' %}
                    <tr>
                        <th>Boy Rank</th>
                        <td><h3>{{ name.boy_rank|linebreaks }}</h3></td>
                    </tr>
                    {% endif %}
                    {% if name.gender in 'Female,Unisex' %}
                    <tr>
                        <th>Girl Rank</th>
                        <td><h3>{{ name.girl_rank|linebreaks }}</h3></td>
                    </tr>
                {% endif %}
            {% endif %}
            {% if name.description %}<tr>
                <th>Description</th>
                <td>{{ name.description|linebreaks }}</td>
            </tr>
            {% endif %}
            {% if name.name_variants %}
            <tr>
                <th>Name Variants</th>
                <td colspan="2">
                    {% for variant in name.name_variants %}
                    <a href="{% url 'app:baby_name_detail' variant %}">{{ variant }}</a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
            {% endif %}
            {% if name.ethnicity %}
            <tr>
                <th>Ethnicity</th>
                <td colspan="2">
                    {% for variant in name.ethnicity %}
                        <a href="{% url 'app:search' %}?ethnicity={{ variant }}">{{ variant }}</a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}</td>
            </tr>
            {% endif %}
            {% if name.religion %}
            <tr>
                <th>Religion</th>
                <td colspan="2">
                            {% for variant in name.religion %}
                        <a href="{% url 'app:search' %}?religion={{ variant }}">{{ variant }}</a>
                        {% if not forloop.last %}, {% endif %}
                {% endfor %}
                </td>
            </tr>
            {% endif %}
            {% if name.language %}
            <tr>
                <th>Language</th>
                <td colspan="2">
                    {% for variant in name.language %}
                        <a href="{% url 'app:search' %}?language={{ variant }}">{{ variant }}</a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </tr>
            {% endif %}
            {% if name.region %}
            <tr>
                <th>Region</th>
                <td colspan="2">
                    {% for variant in name.region %}
                        <a href="{% url 'app:search' %}?region={{ variant }}">{{ variant }}</a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
                </td>
            </tr>
            {% endif %}
        </tbody>
    </table>


    <div class="row">
        <div class="col-6">
            <div class="align-items-center">
                <canvas id="time_series_chart"></canvas>
            </div>
        </div>
        <div class="col-6">
            <div class="align-items-center">
                <div id="chloro" class="responsive-plot"></div>
            </div>
        </div>
    </div>
<!-- Ranking table section -->
<!-- <table class="table">
        <thead>
            <tr>
                <th colspan="3">Rank</th>
            </tr>
            <tr>
                <th>Year</th>
                {% if name.gender == 'Male' or name.gender == 'Unisex' %}
                <th>Boy Rank</th>
                {% endif %}
                {% if name.gender == 'Female' or name.gender == 'Unisex' %}
                <th>Girl Rank</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for row in baby_name_usage_data|slice:"-10:"  %}
            <tr>
                <td>{{ row.year }}</td>
                {% if row.rank_boy is not None %}
                    <td>{{ row.rank_boy|intcomma }}</td>
                {% endif %}
                {% if row.rank_girl is not None %}
                <td>{{ row.rank_girl|intcomma }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    -->


{% if famous_people %}

<h2>Famous {{ name.name }}{% if famous_people|length > 0 %}s{% endif %}</h2>
<table class="table">
    <thead>
        <tr>
        </tr>
    </thead>
    <tbody>
        {% for person in famous_people %}
        <tr>
            <td>{{ person.description|safe }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}



<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% if baby_name_usage_data|length > 2 %}
<script>
// Your data from the backend.
var data = {{baby_name_usage_data|safe}};

// Process the data into arrays.
var years = data.map(function(item) {
  return item.year;
});
var boysData = data.map(function(item) {
  return item.count_boy || null;  // Return null if 'count_boy' is not present
});
var girlsData = data.map(function(item) {
  return item.count_girl || null;  // Return null if 'count_girl' is not present
});

// Create the chart.
var ctx = document.getElementById('time_series_chart').getContext('2d');
var time_series_chart = new Chart(ctx, {
  type: 'line',
  data: {
    labels: years,
    datasets: [{
      label: 'Boys',
      data: boysData,
      backgroundColor: 'rgba(0, 0, 255, 0.1)',  // Blue background
      borderColor: 'rgba(0, 0, 255, 1)',  // Blue border
      borderWidth: 2
    }, {
      label: 'Girls',
      data: girlsData,
      backgroundColor: 'rgba(255, 105, 180, 0.1)',  // Pink background
      borderColor: 'rgba(255, 105, 180, 1)',  // Pink border
      borderWidth: 2
    }]
  },
  options: {
    responsive: true,
    scales: {
      x: {
        title: {
          display: true,
          text: 'Year'
        }
      },
      y: {
        title: {
          display: true,
          text: 'Annual Births'
        }
      }
    }
  }
});
</script>
{% endif %}
{% if states %}
<script>
var data = [{
  type: 'choropleth',
  locationmode: 'USA-states',
  locations: {{states| safe}},
  z: {{relative_popularity}},
  autocolorscale: true,
  reversescale: false,
  marker: {
    line: {
      color: 'rgb(180,180,180)',
      width: 0.5
    },
  },
  colorbar: {
    title: 'Relative Frequency',
  },
}];

var layout = {
  geo:{
    scope: 'usa',
    showlakes: true,
    lakecolor: 'rgba(127,205,255)'
  }
};

Plotly.newPlot('chloro', data, layout, {showLink: false});
</script>
{% endif %}
{% endblock %}

templates/app/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css" rel="stylesheet">

    {% block title %}
        <title>BabyNamer.AI</title>
    {% endblock %}
    {% block header %}
    {% endblock %}
</head>
<body>



{% block nav %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">BabyNamer.AI</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item {% if request.resolver_match.url_name == 'index' %}active{% endif %}">
        <a class="{% if request.resolver_match.url_name == 'index' %}nav-link disabled{% else %}nav-link{% endif %}" href="{% url 'app:index' %}">Top Names</a>
      </li>
      <li class="nav-item {% if request.resolver_match.url_name == 'girls' %}active{% endif %}">
        <a class="{% if request.resolver_match.url_name == 'girls' %}nav-link disabled{% else %}nav-link{% endif %}" href="{% url 'app:girls' %}">Hot Girl Names</a>
      </li>
      <li class="nav-item {% if request.resolver_match.url_name == 'boys' %}active{% endif %}">
        <a class="{% if request.resolver_match.url_name == 'boys' %}nav-link disabled{% else %}nav-link{% endif %}" href="{% url 'app:boys' %}">Hot Boy Names</a>
      </li>
      <li class="nav-item dropdown" id="userActionsDropdown">
        {% if request.user.is_authenticated %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                User Actions
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change password</a>
                <a class="dropdown-item" href="{% url 'accounts:change_profile' %}">Change profile</a>
                <a class="dropdown-item" href="{% url 'accounts:change_email' %}">Change email</a>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
            </div>
      </li>

        {% else %}
      <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Login</a>
      </li>
      <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
    </li>
        {% endif %}
    </ul>
    <form class="form-inline ml-auto" method="get" action="{% url 'app:search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel">Login</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'accounts:login' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" id="username" name="username" required>
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>
          </div>
          <button type="submit" class="btn btn-primary">Login</button>
          <a href="{% url 'accounts:restore_password' %}" class="btn btn-link">Forgot password</a>
        </form>
        <h5 class="modal-dialog">
          <a href="{% url 'accounts:signup' %}">Register</a>
        </h5>
      </div>
    </div>
  </div>
</div>

{% endblock nav %}

{% block messages %}
<div class="alerts">
    {% for message in messages %}

        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message.message }}
        </div>
    {% endfor %}
</div>
{% endblock messages %}

<!-- Content -->
<div class="container">
    {% block content %}
    Thanks for coming!
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    $('.heart').click(function() {
        {% if user.is_authenticated %}
            var heart = $(this);
            var babyNameId = heart.attr('id');
            console.log('Foobar',babyNameId);
            $.post({
                url: '/api/favorite/',
                data: {baby_name_id: babyNameId},
                headers: {'X-CSRFToken': '{{ csrf_token }}'},
                success: function(data) {
                    var heartIcon = heart.find('i'); // changed from 'span' to 'i'
                    if (data.status === 'favorited') {
                        // update the heart icon to a full heart
                        heartIcon.removeClass('bi-heart').addClass('bi-heart-fill');
                    } else if (data.status === 'unfavorited') {
                        // update the heart icon to a grey heart
                        heartIcon.removeClass('bi-heart-fill').addClass('bi-heart');
                    }
                },
                error: function() {
                    // handle error
                    alert('An error occurred. Please try again.');
                }
            });
        {% else %}
            // handle unauthenticated user
            $(".alerts").append("<div class='alert alert-danger' role='alert'>Please <a href='{% url 'accounts:login' %}'>log in</a> or <a href='{% url 'accounts:signup' %}'>sign up</a> to use the favorites feature.</div>");
        {% endif %}
    });
});
</script>

<!-- Bottom Ribbon -->
<div class="footer">
  <p>© BabyNamer.AI {% now "Y" %} - All rights reserved. <a href="{% url 'app:copyright' %}">Copyright Notice</a></p>
</div>

</body>
</html>

templates/app/copyright.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
    <title>Copyright Notice - BabyNamer.AI</title>
{% endblock %}

{% block content %}

{% with 'info@babynamer.ai' as email %}
    <h1>Copyright Information</h1>

    <h2>Ownership of Copyright</h2>
    <p>The copyright in this website and the material on this website (including without limitation the text, computer code, artwork, photographs, images, music, audio material, video material and audio-visual material on this website) is owned by BabyNamer.AI.</p>

    <h2>Copyright License</h2>
    <p>BabyNamer.AI grants to you a worldwide non-exclusive royalty-free revocable license to:
    <ul>
        <li>View this website and the material on this website on a computer or mobile device via a web browser.</li>
        <li>Copy and store this website and the material on this website in your web browser cache memory.</li>
        <li>Print pages from this website for your own personal and non-commercial use.</li>
    </ul>
    BabyNamer.AI does not grant you any other rights in relation to this website or the material on this website. In other words, all other rights are reserved. For the avoidance of doubt, you must not adapt, edit, change, transform, publish, republish, distribute, redistribute, broadcast, rebroadcast or show or play in public this website or the material on this website (in any form or media) without BabyNamer.AI’s prior written permission.</p>

    <h2>Data Mining</h2>
    <p>The automated and/or systematic collection of data from this website is prohibited.</p>

    <h2>Permissions</h2>
    <p>You may request permission to use the copyright materials on this website by writing to {{email }}.</p>

    <h2>Enforcement of Copyright</h2>
    <p>BabyNamer.AI takes the protection of its copyright very seriously. If BabyNamer.AI discovers that you have used its copyright materials in contravention of the license above, BabyNamer.AI may bring legal proceedings against you seeking monetary damages and an injunction to stop you using those materials. You could also be ordered to pay legal costs.</p>
    <p>If you become aware of any use of BabyNamer.AI's copyright materials that contravenes or may contravene the license above, please report this by email to {{email}}.</p>

    <h2>Infringing Material</h2>
    <p>If you become aware of any material on the website that you believe infringes your or any other person's copyright, please report this by email to {{email }}.</p>

    <hr>

    <p>© BabyNamer.AI {% now "Y" %}  - All rights reserved.</p>

    <p><a href="/">Return to Home</a></p>
{% endwith %}

{% endblock %}

templates/app/index.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
    <title>Top Baby Names - BabyNamer.AI</title>
{% endblock %}

{% block content %}
  <table>
  <tbody>
      {% for name_row in names %}
        <tr>
            {% for name in name_row %}
            <td>
                {% include "app/baby_name_card.html" %}
            </td>
            {% endfor %}
        </tr>
      {% endfor %}
  </tbody>
</table>

<div class="pagination">
    <div class="btn-group" role="group" aria-label="Item pagination">

    <span class="step-links">

        {% if page_obj.has_previous %}
            <a href="?page=1"  class="btn btn-outline-primary">first</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
        {% endif %}
    </span>
        </div>
</div>
{% endblock %}

templates/app/register.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}

templates/app/search.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
    <title>Top Baby Names - BabyNamer.AI</title>
{% endblock %}

{% block content %}
<form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>

{% if names %}
    <ul>
        {% for name in names %}
            <li><a href="/{{ name.name }}/">{{ name.name }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No names found.</p>
{% endif %}
{% endblock %}
```

templates/app/stats.html
{% extends "app/base.html" %}
{% load static %}
{% block title %}
    <title>Top Baby Names - BabyNamer.AI</title>
{% endblock %}

{% block content %}
<h1> hello world</h1>
{% for stat in data %}
    {% for k,v in stat %}
    <p>{{ k }} : {{ v }}</p>
    {% endfor %}
{% endfor %}
{% endblock %}
```